config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "articles#index"

  resources :articles
  resources :users, except: [:new]
  
  get 'signup', to: "users#new"

  get "login", to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  validates :name, 
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}

  has_secure_password
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must loggin to perform that action."
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index]
  def index
    #debugger
    @articles = Article.paginate(page: params[:page], per_page: 2)
    if @articles.empty?
      flash[:notice] = "No record on page #{params[:page]}"
    end
  end

  def show
      @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit

  end
  
  def update    
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    if @article.destroy
      flash[:notice] = "Article was successfully deleted"
      redirect_to articles_path
    else
      flash[:notice] = "Article couldn't delete"
    end
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :description, :user)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #debugger
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to users_path(user)
    else
      flash.now[:danger] = "There was something wrong with our login information"
      render 'new'
    end
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
      flash.now[:success] = "You have successfully logged out"
      render "new"
    else
      flash[:notice] = "You are not log in yet"
      render "new"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    # debugger
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has successfully created"
      redirect_to users_path
    else 
      flash[:danger] = "Can't signup for new user"
      render "new"
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "User has update successfully"
      redirect_to users_path
    else
      render "edit"
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "User has deleted with name #{@user.name}"
      redirect_to users_path
    else
      
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <%@article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %></br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/create.html.erb
<h1>Create a new article.</h1>

<%= render 'form' %>

app/views/articles/edit.html.erb
<h1>Edit a new article.</h1>
<%= render 'form' %>
<%= link_to 'Back to Articles', articles_path %>
<p><%= @article.inspect %></p>

app/views/articles/index.html.erb
<h1>This is index articles.</h1>
<div align="center">
  <%= will_paginate %>
</div>
<table id="customers">
  <tr>
    <th>Title</th>
    <th>Created by:</th>
    <th>Description</th>
    <th>Action<%= link_to 'New Article', new_article_path %></th>
  </tr>
<% @articles.each do |article| %>  
  <tr>
    <td><%= article.title %></td> 
    <td><%= article.user.name if article.user %></td>
    <td><%= article.description %></td>
    <td>
      <%= link_to 'Edit', edit_article_path(article) %>|
      <%= link_to 'Show', article_path(article) %> |
      <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "are u sure?"} %>
    </td>
  </tr>
<% end %>
</table>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article.</h1>
<%= render 'form' %>
<%= link_to 'Back to Articles', articles_path %>

app/views/articles/show.html.erb
<h1> This is article show</h1>

<p>
  Title: <%= @article.title %>
</p>
<p>
  Description: <%= @article.description %>
</p>
<%= link_to 'Back to home', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/messages' %>
    <%= yield %>
    
    <div style="bottom: 0;position: fixed;width: 100%"><hr>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <%@user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email  %></br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %></br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1> Edit user </h1>
<%= render "form" %>

<%= link_to "Back", users_path %>

app/views/users/index.html.erb
<h1> Index page for user</h1>
<%= link_to 'New user', {:action => :new} %>
<% @users.each do |u| %>
<ul>
  <li>User id:<%= u.id %></li>
  <li>Username: <%= u.name %> </li>
  <li>Email: <%= u.email %></li>
  <li>Action:<%= link_to "Edit", edit_user_path(u) %>|<%= link_to "Delete", u,:confirm => "Are you sure?", :method => "delete"  %></li>
</ul>
<% end %>
<%= link_to "Log out", logout_path, method: :delete %>

app/views/users/new.html.erb
<h1> Create new user </h1>
<%= render "form" %>